### ISSUE TITLE
Invalid request from Ubercart

### ISSUE THREAD

**Issue by lsolesen** [xendk/quickpay#9]
When I use it for Ubercart, I get the following (I've chosen two payment types), after I click Continue to Quickpay. So the quickpay payment window gives me the following.

```
Invalid request
Please correct the following error:

Invalid payment method lock: The payment method lock filters out all payment methods.
```

**Comment by xendk** [comment]
Sure you've configured it properly? I got that error and wondered what the problem was, until I figured out that I'd only enabled dankort, but not Nets as an acquirer.

The card lock stuff should be exactly the same for both Commerce and Übercart.

**Comment by lsolesen** [comment]
Using the same account. And enabled the same cards. Will investigate again.
Den 16/03/2016 20.10 skrev "Thomas Fini Hansen" notifications@github.com:

**Comment by xendk** [comment]
I've just looked the code over, and card lock is an issue between settings_form and form, which is both defined in the Quickpay object that they both use. I have no idea how uc_quickpay could mess with it.

**Comment by lsolesen** [comment]
Hm. Had both visa and dk enabled. However after enabling mc also it worked
